server:
  port: 8062
  ssl:
    key-store-password: sharad
    key-store-type: PKCS12
    key-alias: myapp
    key-store: classpath:keystore.p12

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          filters:
            - StripPrefix=1
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
        - id: product-service
          filters:
            - StripPrefix=1
          uri: lb://product-service
          predicates:
            - Path=/product-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8060/eureka/
